server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inno_info?useUnicode=true&characterEncoding=utf8&useTimezone=true&serverTimezone=GMT
    username: joker
    password: joker
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

jwt:
  header: token   #jwt的请求头
  secret: eyJleHAiOjE1NDMyMDUyODUsInN1YiI6ImFkbWluIiwiY3Jl   #jwt的加密字符串
  expiration: 3600000   #jwt token有效时间（毫秒）一个小时
